### ISSUE TITLE
slbt_dump_machine_child doesn't work with compiler wrappers

### ISSUE THREAD

**Issue by raphaelcohn** [midipix-project/slibtool#2]
`slbt_dump_machine_child` doesn't work with compiler wrappers such as `ccache` or `distcc`, as it assumes the compiler to use is contained solely in the first argument.

**Comment by midipix** [comment]
Two questions: first, can you give an example of what the proper distcc invocation would be? Second, what would be a good way to support this? Ideally I'd like the solution to be generic enough, making it unnecessary to encode knowledge about individual wrappers.

**Comment by raphaelcohn** [comment]
For ccache, I'd normally be passing `CC` as `CC='ccache cc OPTIONS'`. I'm
not actually completely sure of the best way to support this. Right now,
I've switched over to using a wrapper script, which solves this problem
nicely. ccache can also be used via symlink, but it's easy to get really
quite confused with this approach. Perhaps the 'right' solution would
simply be a note or warning in the README, and for an invalid
'-dumpmachine' response to produce an error (it'd be nice to see the exec
to -dumpmachine on stderr like for the other commands - it took me an age
to track down (:-) ).

For interest, I'm trying to use slibtool with musl-cross-make and ccache.
If there was ever an use case... It's been fun - it certainly speeds things
up very much indeed. Thank you so much for writing a neat, tidy replacement
for the absolute horror that is libtool. Now if I could only persuadce you
to kill off the rest of autocruft...

Two questions: first, can you give an example of what the proper distcc

**Comment by midipix** [comment]
> Perhaps the 'right' solution would simply be a note or warning in the README, and for an invalid '-dumpmachine' response to produce an error (it'd be nice to see the exec to -dumpmachine on stderr like for the other commands

Using a script that invokes ccache/distcc on your behalf is indeed one good solution, namely since it keeps the compiler wrapper transparent to slibtool. I'll add a comment to the readme file and make the -dumpmachine output more useful. In addition, one item on my todo list is to display a simple trace upon failure, I guess that would have saved you quite a bit of time:-)

> Now if I could only persuadce you to kill off the rest of autocruft...

:-) well for new projects take a look of slibtool's own build system, which can be easily derived from `sofort` (also) via the `sofort.sh` script (git://midipix.org/sofort). If you find the build system useful and need anything to be added or changed let me know. The build system (as well as sofort.sh) have thus far saved me quite a bit of time, so hopefully they could save others some time as well.

**Comment by raphaelcohn** [comment]
sfort's quite nice looking and very clean. It needs minimal command line tools (and, with the odd change here or there, possibly even fewer - such as `dirname` and `touch`) - which makes it a nice way to bootstrap code.

**Comment by midipix** [comment]
As of commit 34988f8, slibtool supports arbitrary compiler wrappers via --ccwrap , as well as the so-called known wrappers with no preceding switch, as supported by gnu libtool.
